# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20171004_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='files'),
        ),
    ]
