# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_java'),
    ]

    operations = [
        migrations.AddField(
            model_name='c',
            name='videosource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='java',
            name='videosource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
            preserve_default=False,
        ),
    ]
