# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20171006_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='videofile',
        ),
    ]
