# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20171006_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='c',
            name='course',
        ),
        migrations.AddField(
            model_name='video',
            name='videofile',
            field=models.FileField(default=1, upload_to='files'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='c',
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.course'),
            preserve_default=False,
        ),
    ]
