# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='about',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
    ]
