# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_member_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='about',
        ),
    ]
