# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_member_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_pic',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
