# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_member_member_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_pic',
        ),
    ]
