# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_member1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member1',
        ),
    ]
