# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_delete_member1'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=1000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.member')),
            ],
        ),
    ]
