# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='member',
        ),
        migrations.DeleteModel(
            name='note',
        ),
    ]
