# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20170926_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
