# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_member_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='picture',
        ),
    ]
