# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_delete_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='member1',
            new_name='member',
        ),
    ]
