# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_remove_member_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='member1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='pic',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
