# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_auto_20170927_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='reg_no',
            field=models.FileField(max_length=8, upload_to=''),
        ),
    ]
