# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_auto_20170927_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='reg_no',
            new_name='pic',
        ),
    ]
