# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_auto_20170927_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='pic',
        ),
        migrations.AddField(
            model_name='member',
            name='reg_no',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
