# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0022_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
