# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0025_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
