# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0029_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
