# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0030_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.FileField(default=0, upload_to='files'),
        ),
    ]
