# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0032_remove_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='reg_no',
            field=models.FileField(upload_to='files'),
        ),
    ]
