# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0034_auto_20171022_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='img',
            new_name='reg_no',
        ),
    ]
