# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.FileField(upload_to='files'),
        ),
    ]
