# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170930_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.ImageField(upload_to=''),
        ),
    ]
